### ISSUE TITLE
URL Mapping Edeka24

### ISSUE THREAD

**Issue by simonneutert** [simonneutert/kohldampfmaschine#5]
## Prämisse
Zur Verfügung steht eine JSON Datei, sie beinhaltet mindestens die Felder:

* __URL__ zum Produkt auf Edeka24
* __Name__ des Produkts
* __Name__ des Produkts downcased, sorted, digits and regular word characters, no spaces

## Datenset
_optionale Felder:_
* __Kategorie__ des Produkts

```json
{
  "https://www.edeka24.de/Drogerie/Reiniger/Biff-Bad-Hygiene-Total-750-ml.html": {
    "name": "Biff Bad Hygiene Total 750 ml",
    "url": "https://www.edeka24.de/Drogerie/Reiniger/Biff-Bad-Hygiene-Total-750-ml.html",
    "signature": "057aabbdeeffghiillmnotty"
  },
  "https://www.edeka24.de/Drogerie/Koerperpflege-oxid/Duschgel-Duschbad/Tetesept-Meeressalz-Ruecken-Schulter.html": {
    "name": "Tetesept Meeressalz Ruecken Schulter",
    "url": "https://www.edeka24.de/Drogerie/Koerperpflege-oxid/Duschgel-Duschbad/Tetesept-Meeressalz-Ruecken-Schulter.html",
    "signature": "acceeeeeeeeehkllmnprrrssssttttuuz"
  }
}
```

## Ziel

Entwicklung eines Algorithmus, um Produkte aus der Zutatenliste dynamisch auf Edeka zu verlinken.

Sprachen: Ruby (Backend) oder Javascript (Frontend, __ohne jQuery__)

__html5 tag__ `<e24></e24>` das den Text der Zutaten umspannt.

#### Regex / Word Match

Über das Feld `name_downcased_digits_words_unspaced` die Übereinstimmung errechnen und einen Score berechnen. Die höchste Übereinstimmung wird als Link auf das Produkt der Zutatenliste mit der URL aus der JSON Datei gemappt.

**Comment by phroggar** [comment]
https://www.100partnerprogramme.de/p/edeka24-de-1460/

**Comment by simonneutert** [comment]
@phroggar dynamic linking im alpha stadium ist vor wenigen Minuten online gegangen 💪 

der code ist noch unaufgeräumt, läuft aber 🙌 😅
